namespace Jmodot.Core.Input;

using Godot;
using GCol = Godot.Collections;

/// <summary>
/// A Resource that defines a complete input mapping for a single player.
/// It acts as a data container, bridging abstract InputActions (like "Move" or "Jump")
/// to the specific Godot InputMap action strings that should trigger them.
/// Instances of this are either created manually (for keyboards) or generated by the
/// InputMapGenerator tool (for gamepads).
/// </summary>
[GlobalClass, Tool]
public partial class InputMappingProfile : Resource
{
    [Export]
    public GCol.Array<ActionBinding> ActionBindings { get; set; } = new();

    [Export]
    public GCol.Array<VectorActionBinding> VectorBindings { get; set; } = new();
}
