namespace Jmodot.Core.Combat;

/// <summary>
/// Holds transient data about the hit interaction.
/// Generated by the Hurtbox and consumed by CombatEffects.
/// </summary>
public class HitContext
{
    /// <summary>
    /// The root owner of the attack (e.g., The Player).
    /// </summary>
    public Node Attacker { get; set; }

    /// <summary>
    /// The specific object causing the hit (e.g., The Arrow, The Sword, The Trap).
    /// </summary>
    public Node Source { get; set; }
}
