namespace Jmodot.Core.Combat;

/// <summary>
/// Holds transient data about the hit interaction.
/// Generated by the Hurtbox and consumed by CombatEffects.
/// </summary>
public class HitContext
{
    /// <summary>
    /// The root owner of the attack (e.g., The Player).
    /// </summary>
    public Node Attacker { get; set; }

    /// <summary>
    /// The specific object causing the hit (e.g., The Arrow, The Sword, The Trap).
    /// </summary>
    public Node Source { get; set; }

    /// <summary>
    /// The normalized direction from the Source/Attacker to the Victim.
    /// Used for determining knockback direction.
    /// </summary>
    public Vector3 HitDirection { get; set; }

    /// <summary>
    /// The linear velocity of the Source at the moment of impact.
    /// Used for calculating dynamic force (e.g. speed-based knockback).
    /// </summary>
    public Vector3 ImpactVelocity { get; set; }

    /// <summary>
    /// The world-space position of the attack's epicenter (e.g., hitbox center).
    /// Used for distance-based damage/knockback falloff calculations.
    /// </summary>
    public Vector3 EpicenterPosition { get; set; }

    /// <summary>
    /// The distance from the epicenter to the hurtbox center.
    /// Pre-calculated for convenience in effect calculations.
    /// </summary>
    public float DistanceFromEpicenter { get; set; }
}
