namespace Jmodot.Core.Combat;

using Jmodot.Core.Health;

/// <summary>
/// 2D twin of <see cref="HitContext"/>. Holds transient data about the hit
/// interaction. Generated by a 2D Hurtbox and consumed by CombatEffects.
/// </summary>
public class HitContext2D
{
    /// <summary>
    /// The root owner of the attack (e.g., The Player).
    /// </summary>
    public Node Attacker { get; init; }

    /// <summary>
    /// The specific object causing the hit (e.g., The Arrow, The Sword, The Trap).
    /// </summary>
    public Node Source { get; init; }

    /// <summary>
    /// The normalized direction from the Source/Attacker to the Victim.
    /// Used for determining knockback direction.
    /// </summary>
    public Vector2 HitDirection { get; init; }

    /// <summary>
    /// The linear velocity of the Source at the moment of impact.
    /// Used for calculating dynamic force (e.g. speed-based knockback).
    /// </summary>
    public Vector2 ImpactVelocity { get; init; }

    /// <summary>
    /// The world-space position of the attack's epicenter (e.g., hitbox center).
    /// Used for distance-based damage/knockback falloff calculations.
    /// </summary>
    public Vector2 EpicenterPosition { get; init; }

    /// <summary>
    /// The distance from the epicenter to the hurtbox center.
    /// Pre-calculated for convenience in effect calculations.
    /// </summary>
    public float DistanceFromEpicenter { get; init; }

    /// <summary>
    /// Categorizes the damage cause for downstream feedback filtering. See
    /// <see cref="HitContext.Kind"/> for the rationale.
    /// </summary>
    public DamageKind Kind { get; init; } = DamageKind.Direct;

    public HitContext2D WithKind(DamageKind kind) => new HitContext2D
    {
        Attacker = this.Attacker,
        Source = this.Source,
        HitDirection = this.HitDirection,
        ImpactVelocity = this.ImpactVelocity,
        EpicenterPosition = this.EpicenterPosition,
        DistanceFromEpicenter = this.DistanceFromEpicenter,
        Kind = kind,
    };
}
